# Dockerfile.frontend
FROM node:20

WORKDIR /app

COPY ./circuit-composer-frontend/ /app/

RUN npm install
RUN npm run build

# Serve build with a simple static server
RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]