# Dockerfile.backend
FROM python:3.10

WORKDIR /app

COPY ./circuit-composer-backend/ /app/

RUN pip install --upgrade pip
RUN pip install fastapi uvicorn qiskit qiskit-aer matplotlib

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]